DROP TABLE IF EXISTS Accounts;
DROP TABLE IF EXISTS Bank_Accounts;
DROP TABLE IF EXISTS Transactions;
DROP TABLE IF EXISTS Automatic_Payments;
DROP TABLE IF EXISTS loans;
DROP TABLE IF EXISTS morgatges;
